#!/usr/bin/env bash
# installs nginx and configure it to listens on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permaent;' /etc/nginx/sites-available/default
sudo service nginx start
