#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
# Your script should only display:username, user id, path for the user

file=/etc/passwd

while read -r line; do
  echo "$line" | cut -f 1,3,6 -d ':'
  done < "$file"
