#!/usr/bin/env bash
# Write a Bash script that displays:
# script that gives you information about the bestschool file.

i="school"
if [ -e "$i" ]
then
    echo "$i file exists"
        if [ -s "$i" ]
	    then
		echo "$i file is not empty"
		    else
			echo "$i file is empty"
			    fi
			        if [ -f "$i" ]
				    then
					echo "$i is a regular file"
					    fi
					    else
					        echo "$i file does not exist"
						fi
